# Build and Push OCI image to GHCR
# =============================================================================
# Build the OCI container image with docker and tag the image with SemVer
# provided by the tag name.
# Then proceed to push the image to the GHCR.
#

name: Build and Push to GHCR
on:
    push:
        tags:
            - v*.*.*
env:
    REGISTRY: ghcr.io
    IMAGE_NAME: brunsviga13rk/emulator
jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout
              uses: actions/checkout@v5
              with:
                  submodules: "recursive"
            - name: Log in to the Container registry
              uses: docker/login-action@v3
              with:
                  registry: ${{ env.REGISTRY }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
            - name: Extract metadata for Docker
              id: meta
              uses: docker/metadata-action@v5
              with:
                  images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
                  tags: |
                      type=semver,pattern={{version}}
            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                  context: .
                  push: true
                  tags: ${{ steps.meta.outputs.tags }}
                  labels: ${{ steps.meta.outputs.labels }}
