name: release-please
on:
    push:
        branches:
            - main
jobs:
    release-please:
        runs-on: ubuntu-latest
        outputs:
            release_created: ${{ steps.release.outputs.release_created }}
            tag_name: ${{ steps.release.outputs.tag_name }}
        steps:
            - uses: googleapis/release-please-action@v4
              id: release
              with:
                  token: ${{ secrets.RELEASE_PLEASE_TOKEN }}
                  release-type: simple
    release-artifact:
        runs-on: ubuntu-latest
        needs: release-please
        if: ${{ needs.release-please.outputs.release_created }}
        permissions:
            contents: write
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
              with:
                  submodules: recursive
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version-file: '.nvmrc'
            - name: Clean Install
              run: npm ci
            - name: Build Project
              run: make build
            - name: Prepare Artifact
              run: |
                  zip -r dist.zip ./dist
            - name: Upload Release Artifact
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: gh release upload ${{ needs.release-please.outputs.tag_name }} ./dist.zip
